  <div class="separator p-2"></div>


  </main>

  <footer class="bg-dark text-white text-center p-2">
    <small>mgp battle &copy; 2021-2022</small>
  </footer>

  <!-- Bootstrap JS & Popper -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
    integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
    integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous">
  </script>

  <!-- Custom JS -->
  <script src="public/js/utils.js"></script>
  <script src="public/js/keyboard.js"></script>
  <script src="public/js/modal_toggler.js"></script>
  <script src="public/js/page_menu.js"></script>
  <script src="public/js/countdown.js"></script>
  <script src="public/js/addresult.js"></script>
  <script src="public/js/rider_info.js"></script>
  <script src="public/js/rider_activation.js"></script>


  <script src="public/js_stats/main.js" type="module"></script>


  <!--
<script src="assets/js/stats_comment_toggler.js"></script>
<script src="assets/js/stats_selector.js"></script>
<script src="assets/js/confetti.js"></script>
-->


  </body>


  </html>