<!-- T*T -- Bet modal -->

<div class="modal fade" id="betModal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <div class="modal-body text-center">
        <i class="fas fa-flag-checkered fa-2x"></i>
        <p class="mt-3">Votre pronostic a bien été enregistré. <br>Bonne course !</p>
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>









<!-- A*A -- [S] bet type (PRONOSTIC / RESULTAT) -->
<!-- BUG -- DISPLAY NONE -->
<section id="betType" class="disp-bd d-none">
  <!-- <small class="vst">#betType</small> -->

  <div class="container">
    <div class="row">
      <div class="col-12">
        <p class="fw-bold text-center text-danger fs-3"><?php if ($_SESSION['type'] !== 'ADM') {
                                                          echo 'Pronostic';
                                                        } else {
                                                          echo 'Résultat';
                                                        } ?></p>
      </div>
    </div>
  </div>
</section>



<!-- A*A -- [S] bet page current event -->
<section id="betCurrentEvent" class="disp-bd">
  <!-- <small class="vst">#betCurrentEvent</small> -->
  <div class="container">
    <div class="row">
      <div class="col-12 text-center mb-3">
        <p class="fw-bold mb-0">#<?= $idRace ?></p>
        <p class="fw-bold mb-0">Grand Prix <?= $fullNameRace ?></p>
        <img src="public/assets/flags/<?= $_SESSION['flagCurrRace'] ?>" alt="" class="flag-img">
      </div>
    </div>
  </div>

</section>









<!-- A*A -- [S] bet form -->
<section id="betForm" class="disp-bd">
  <!-- <small class="vst">#betForm</small> -->

  <div class="container">
    <div class="row">
      <div class="col-12">


        <!-- MK -- message d'erreur en cas de pronostic invalide -->
        <div id="betAlertContainer">
          <div class="alert alert-danger text-center w-75 mx-auto my-0
              <?php
              if ($alert == "") {
                echo 'd-none';
              } else {
                echo 'd-block';
              } ?>">
            <i class="fas fa-exclamation-triangle"></i>
            <small class="d-block"><?= $alert ?></small>
          </div>
        </div>







        <form action="bet.php" method="POST">


          <div class="mb-5">
            <!-- conteneur des selects -->


            <!-- RPR -- Position #1 -->
            <div class="input-group mb-2">
              <label for="pos1" class="input-group-text">1°</label>
              <select name="pos1" id="pos1" class="form-select">

                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos1'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";

                  if ($_POST && ($_POST['pos1'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }


                  if (isset($_GET['pos1']) && ($_GET['pos1'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>


              </select>
            </div>


            <!-- RPR -- Position #2 -->
            <div class="input-group mb-2">
              <label for="pos2" class="input-group-text">2°</label>
              <select name="pos2" id="pos2" class="form-select">


                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos2'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";


                  if ($_POST && ($_POST['pos2'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }


                  if (isset($_GET['pos2']) && ($_GET['pos2'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>


              </select>
            </div>


            <!-- RPR -- Position #3 -->
            <div class="input-group mb-2">
              <label for="pos3" class="input-group-text">3°</label>
              <select name="pos3" id="pos3" class="form-select">


                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos3'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";


                  if ($_POST && ($_POST['pos3'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }


                  if (isset($_GET['pos3']) && ($_GET['pos3'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>


              </select>
            </div>


            <!-- RPR -- Position #4 -->
            <div class="input-group mb-2">
              <label for="pos4" class="input-group-text">4°</label>
              <select name="pos4" id="pos4" class="form-select">


                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos4'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";


                  if ($_POST && ($_POST['pos4'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }


                  if (isset($_GET['pos4']) && ($_GET['pos4'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>


              </select>
            </div>


            <!-- RPR -- Position #5 -->
            <div class="input-group mb-2">
              <label for="pos5" class="input-group-text">5°</label>
              <select name="pos5" id="pos5" class="form-select">

                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos5'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";


                  if ($_POST && ($_POST['pos5'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }


                  if (isset($_GET['pos5']) && ($_GET['pos5'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>

              </select>
            </div>



            <!-- RPR -- Position #6 -->
            <div class="input-group mb-2">
              <label for="pos6" class="input-group-text">6°</label>
              <select name="pos6" id="pos6" class="form-select">

                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos6'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";

                  if ($_POST && ($_POST['pos6'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }

                  if (isset($_GET['pos6']) && ($_GET['pos6'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>

              </select>
            </div>



            <!-- RPR -- Position #7 -->
            <div class="input-group mb-2">
              <label for="pos7" class="input-group-text">7°</label>
              <select name="pos7" id="pos7" class="form-select">

                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos7'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";

                  if ($_POST && ($_POST['pos7'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }

                  if (isset($_GET['pos7']) && ($_GET['pos7'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>

              </select>
            </div>



            <!-- RPR -- Position #8 -->
            <div class="input-group mb-2">
              <label for="pos8" class="input-group-text">8°</label>
              <select name="pos8" id="pos8" class="form-select">

                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos8'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";

                  if ($_POST && ($_POST['pos8'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }

                  if (isset($_GET['pos8']) && ($_GET['pos8'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>

              </select>
            </div>



            <!-- RPR -- Position #9 -->
            <div class="input-group mb-2">
              <label for="pos9" class="input-group-text">9°</label>
              <select name="pos9" id="pos9" class="form-select">

                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos9'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";

                  if ($_POST && ($_POST['pos9'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }

                  if (isset($_GET['pos9']) && ($_GET['pos9'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>

              </select>
            </div>


            <!-- RPR -- Position #10 -->
            <div class="input-group mb-2">
              <label for="pos10" class="input-group-text">10°</label>
              <select name="pos10" id="pos10" class="form-select">

                <option value="noRider" <?php
                                        if (!$_POST || $_POST['pos10'] === 'noRider') {
                                          echo 'selected';
                                        }
                                        ?>>---</option>
                <?php
                foreach ($allRiders as $rider) {
                  $value = $rider['idRider'];
                  $text = "#" . $rider['numRider'] . " - " . $rider['lsNameRider'] . " " . substr($rider['fsNameRider'], 0, 1) . ".";

                  if ($_POST && ($_POST['pos10'] === $value)) {
                    $selected = "selected";
                  } else {
                    $selected = "";
                  }

                  if (isset($_GET['pos10']) && ($_GET['pos10'] === $value)) {
                    $selected = "selected";
                  }
                  echo "<option value='$value' $selected>$text</option>";
                }
                ?>

              </select>
            </div>




          </div> <!-- fin du conteneur des selects -->







          <!-- TODO -- activation du bouton UNIQUEMENT si les 5 champs sont renseignés -->
          <button name="submitBet" id="submitBet" class="btn btn-outline-dark d-block w-100">GO !!!</button>


        </form>

      </div>
    </div>
  </div>