<section>
  <div class="container">
    <div class="row my-3">
      <div class="col-12 fsz875">

        <p class="fw-bold text-center fs-6">Notre devise : ce n'est qu'un jeu !</p>

        <p>Aucun coût d’inscription, ni frais, ni gain d’argent… 
          <br>Juste le plaisir de faire des pronostics et découvrir qui est le plus fort.</p>

        <p class="fw-bold text-center fs-6">Le jeu</p>



        <p>À l'occasion de chaque course, chaque concurrent envoie un pronostic via son espace personnel avec les 10 premiers pilotes de la catégorie Motogp.</p>

        <p>L’envoi du pronostic est possible à partir de la première séance d’essais libres (le vendredi) jusqu’à <strong>15 minutes avant le départ</strong> de la course.
          <br>Le pronostic pourra être modifié plusieurs fois dans ce créneau, seul le dernier sera pris en compte.
        </p>

        <p>Si la course devait être décalée en raison des conditions météo, ou accident, ou toute autre raison, les pronostics ne pourront être modifiées que si la course est reportée à une date ultérieure.</p>

        <p>Si un concurrent n'envoie pas de pronostic pour une course dans les délais prévus, son pronostic du grand prix précédent sera pris en compte.</p>



        <p class="fw-bold text-center fs-6">Les points</p>


        <p class="fw-bold text-gray1 m-0">
          <i class="fas fa-star text-greenlight fs-5 me-2"></i>
          Pilotes BIEN PLACÉS
        </p>
        <p>Les pilotes bien placés dans le pronostic auront les points de la motogp : 25 pour le 1er, 20 pour le 2ème, 16 pour le 3ème...
          <br>puis respectivement 13, 11, 10, 9, 8, 7, 6 points.
        </p>


        <p class="fw-bold text-gray1 m-0">
          <i class="fas fa-square text-orange fs-5 me-2"></i>
          Pilotes MAL PLACÉS PODIUM
        </p>
        <p>Les pilotes pronostiqués sur le podium qui arrivent sur le podium, mais pas à la même position que dans le pronostic, auront 9 points.</p>


        <p class="fw-bold text-gray1 m-0">
          <i class="fas fa-circle text-yellow fs-5 me-2"></i>
          Pilotes MAL PLACÉS
        </p>
        <p>Dans tous les autres cas, les pilotes mal placés auront 4 points.</p>


        <p class="fw-bold text-gray1 m-0">
          <i class="fas fa-times text-gray2 fs-5 me-2"></i>
          Pilotes NON PLACÉS
        </p>
        <p>Les pilotes qui arrivent après la 10<sup>e</sup> position, ou qui ne terminent pas la course, auront 0 points.</p>

        <p class="my-0">Quelques exemples :</p>
        <ul style="padding: 1rem;">
          <li>
            <p class="m-0">un pilote qui a été pronostiqué 4ème et qui arrive 4ème aura 13 points (c'est un BIEN PLACÉ)</p>
          </li>
          <li>
            <p class="m-0">un pilote qui a été pronostiqué 1er et qui arrive 2ème ou 3ème aura 9 points (c'est un MAL PLACÉ PODIUM)</p>
          </li>
          <li>
            <p class="m-0">un pilote qui a été pronostiqué 4ème et qui arrive 1er, 2ème ou 3ème aura 4 points (c'est un MAL PLACÉ)</p>
          </li>
          <li>
            <p class="m-0">un pilote qui a été pronostiqué 2ème et qui arrive 5ème aura 4 points (c'est un MAL PLACÉ)</p>
          </li>
          <li>
            <p class="m-0">un pilote qui a été pronostiqué 6ème et qui arrive 11ème aura 0 points (c'est un NON PLACÉ)</p>
          </li>
        </ul>



        <p class="fw-bold text-gray1 m-0">
          <i class="fas fa-flag-checkered text-red fs-5 me-2"></i>
          Victoire de manche
        </p>
        <p>Le ou les concurrent(s) qui remportent le plus haut score sur une course, reçoivent une victoire de manche.</p>


        <p class="fw-bold text-center fs-6">Résultat de la course</p>

        <p>Afin d’avoir des points certains pour notre classement et éviter toute attente liée à des décisions longues, nous allons prendre en compte les placements officiels avec les possibles pénalités données avant la minuit du jour de la course (heure du pays o le grand prix a lieu).</p>
        <p>En cas de situation particulièrement compliquée ou épineuse, nous déciderons au cas par cas et pourrions proposer un choix par vote aux participants.</p>


        <p class="fw-bold text-center fs-6">En cas d'égalité</p>

        <p>En cas d'égalité de points entre 2 ou plusieurs concurrents, leur position respective au classement sera déterminée en fonction des critères suivants, dans l'ordre :</p>

        <ul>
          <li>nombre de victoires de manche</li>
          <li>nombre total de bien placés</li>
          <li>nombre total de mal placés podium</li>
          <li>nombre total de mal placés</li>
          <li>nombre total de 1<sup>ers</sup> bien placés</li>
          <li>nombre total de 2<sup>èmes</sup> bien placés</li>
          <li>nombre total de 3<sup>èmes</sup> bien placés</li>
          <li>nombre total de 4<sup>èmes</sup> bien placés</li>
          <li>nombre total de 5<sup>èmes</sup> bien placés</li>
          <li>nombre total de 6<sup>èmes</sup> bien placés</li>
          <li>nombre total de 7<sup>èmes</sup> bien placés</li>
          <li>nombre total de 8<sup>èmes</sup> bien placés</li>
          <li>nombre total de 9<sup>èmes</sup> bien placés</li>
          <li>nombre total de 10<sup>èmes</sup> bien placés</li>
        </ul>


      </div>
    </div>
  </div>
</section>




<section class="my-5">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">

        <a class="x-link" href="loginsuper.php?action=connect&super=yes">
          <i class="fas fa-flag-checkered text-gray2 mx-2"></i>
        </a>


        <i class="fas fa-flag-checkered text-gray2 mx-2"></i>
        <i class="fas fa-flag-checkered text-gray2 mx-2"></i>

      </div>
    </div>
  </div>
</section>