<section id="racePageCurrentEvent">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center mb-5">
        <p class="fw-bold mb-0">#<?= $_SESSION['idCurrRace'] . " - GP " . $_SESSION['fullNameCurrRace'] ?></p>
      </div>
    </div>
  </div>
</section>


<!-- T*T -- affichage des phases -->
<section>
  <div class="container">


    <!-- RPR -- phase #0 -->
    <div class="row my-2">
      <div class="col-2">
        <i class="fas fa-circle fa-2x text-gray2"></i>
      </div>

      <div class="col-1 ps-0 <?php
                              if ($progRace !== 'white') echo 'd-none';
                              ?>">
        <i class="fas fa-caret-left fa-2x text-dark"></i>
      </div>


      <div class="col-9 ps-0 <?php
                              if ($progRace !== 'white') echo 'd-none';
                              ?>">
        <div class="alert alert-secondary py-1">
          <small><span class="fw-bold">Phase #0</span>
            <hr class="my-1">
            Le weekend de course n'a pas commencé.<br>
            Les pronostics sont encore <span class="fw-bold">FERMÉS</span>.
          </small>
        </div>
      </div>

    </div> <!-- end of phase 0 -->



    <!-- RPR -- phase #1 -->
    <div class="row my-2">
      <div class="col-2">
        <i class="fas fa-circle fa-2x text-success"></i>
      </div>

      <div class="col-1 ps-0 <?php
                              if ($progRace !== 'green') echo 'd-none';
                              ?>">
        <i class="fas fa-caret-left fa-2x text-dark"></i>
      </div>

      <div class="col-9 ps-0 <?php
                              if ($progRace !== 'green') echo 'd-none';
                              ?>">
        <div class="alert alert-success py-1">
          <small><span class="fw-bold">Phase #1</span>
            <hr class="my-1">
            La course n'a pas démarré.<br>
            Les pronostics sont <span class="fw-bold">OUVERTS</span>.
          </small>
        </div>
      </div>

    </div> <!-- end of phase 1 -->




    <!-- RPR -- phase #2 -->
    <div class="row my-2">
      <div class="col-2">
        <i class="fas fa-circle fa-2x text-warning"></i>
      </div>


      <div class="col-1 ps-0 <?php
                              if ($progRace !== 'yellow') echo 'd-none';
                              ?>">
        <i class="fas fa-caret-left fa-2x text-dark"></i>
      </div>


      <div class="col-9 ps-0 <?php
                              if ($progRace !== 'yellow') echo 'd-none';
                              ?>">
        <div class="alert alert-warning py-1">
          <small><span class="fw-bold">Phase #2</span>
            <hr class="my-1">
            La course a commencé.<br>
            Les pronostics sont <span class="fw-bold">BLOQUÉS</span>.
          </small>
        </div>
      </div>


    </div>




    <!-- RPR -- phase #3 -->
    <div class="row my-2">
      <div class="col">
        <i class="fas fa-circle fa-2x text-danger"></i>
      </div>


      <div class="col-1 ps-0 <?php
                              if ($progRace !== 'red') echo 'd-none';
                              ?>">
        <i class="fas fa-caret-left fa-2x text-dark"></i>
      </div>


      <div class="col-9 ps-0 <?php
                              if ($progRace !== 'red') echo 'd-none';
                              ?>">
        <div class="alert alert-danger py-1">
          <small><span class="fw-bold">Phase #3</span>
            <hr class="my-1">
            La course est terminée.<br>
            Les pronostics et les scores sont maintenant visibles pour tous les joueurs.
          </small>
        </div>
      </div>


    </div>


  </div>



  <section class="mt-5">
    <div class="container">

      <div class="row">
        <div class="col">

          <!-- RPR -- formulaire changement de phase -->
          <form action="raceprog.php" method="POST">

            <select name="racePhase" id="racePhase" class="form-select text-center">
              <option value="white" <?php
                                    if ($progRace === 'white') echo 'selected';
                                    if ($progRace === 'green' || $progRace === 'yellow' || $progRace === 'red') echo 'disabled';
                                    ?>>Phase #0</option>
              <option value="green" <?php
                                    if ($progRace === 'green') echo 'selected';
                                    if ($progRace === 'yellow' || $progRace === 'red') echo 'disabled';
                                    ?>>Phase #1</option>
              <option value="yellow" <?php
                                      if ($progRace === 'yellow') echo 'selected';
                                      if ($progRace === 'white' || $progRace === 'red') echo 'disabled';
                                      ?>>Phase #2</option>
              <option value="red" <?php
                                  if ($progRace === 'red') echo 'selected';
                                  if ($progRace === 'white' || $progRace === 'green') echo 'disabled';
                                  ?>>Phase #3</option>
            </select>


            <button type="submit" class="btn btn-outline-dark form-control my-2">Changer de phase</button>


          </form>


        </div>
      </div>
    </div>
  </section>






</section>